const $=s=>document.querySelector(s);
const map={skill:["skillTemplate","skillsList"],service:["serviceTemplate","servicesList"],experience:["experienceTemplate","experienceList"],project:["projectTemplate","projectsList"]};
function addItem(type,v={}){const [t,l]=map[type],n=$("#"+t).content.cloneNode(true),i=n.querySelector(".repeat-item");Object.entries(v).forEach(([k,x])=>{const e=i.querySelector(`[data-field="${k}"]`);if(e)e.value=x??""});i.querySelector(".remove").onclick=()=>i.remove();$("#"+l).appendChild(n)}
document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>addItem(b.dataset.add));
function fill(d){$("#editorForm").reset();["skills","services","experience","projects"].forEach(x=>$("#"+x+"List").innerHTML="");const p=d.profile||{},a=d.about||{},c=d.contact||{},s=c.socials||{},set=(n,v)=>document.querySelector(`[name="${n}"]`).value=v??"";set("name",p.name);set("nickname",p.nickname);set("title",p.title);set("shortDescription",p.shortDescription);set("profileImage",p.image);set("aboutTitle",a.title);set("aboutDescription",a.description);set("email",c.email);set("facebook",s.Facebook);set("linkedin",s.LinkedIn);set("github",s.GitHub);(d.skills||[]).forEach(x=>addItem("skill",x));(d.services||[]).forEach(x=>addItem("service",x));(d.experience||[]).forEach(x=>addItem("experience",x));(d.projects||[]).forEach(x=>addItem("project",x))}
function list(id){return[...document.querySelectorAll("#"+id+"List .repeat-item")].map(i=>{const o={};i.querySelectorAll("[data-field]").forEach(e=>o[e.dataset.field]=e.type==="number"?Number(e.value||0):e.value);return o})}
function data(){const f=$("#editorForm"),v=n=>f.elements[n].value.trim();return{profile:{name:v("name"),nickname:v("nickname"),title:v("title"),shortDescription:v("shortDescription"),image:v("profileImage")},about:{title:v("aboutTitle"),description:v("aboutDescription")},skills:list("skills"),services:list("services"),experience:list("experience"),projects:list("projects"),contact:{email:v("email"),socials:{Facebook:v("facebook"),LinkedIn:v("linkedin"),GitHub:v("github")}}}}
function download(){const b=new Blob([JSON.stringify(data(),null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="portfolio.json";a.click();URL.revokeObjectURL(u)}
$("#downloadBtn").onclick=download;$("#downloadBtnBottom").onclick=download;
$("#importFile").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{fill(JSON.parse(await f.text()))}catch{alert("This is not a valid portfolio.json file.")}};